[pytest]

# ============================================================
# ⚙️ НАСТРОЙКИ ЗАПУСКА
# ============================================================
addopts =
    -s
    --clean-alluredir
    --alluredir=allure-results

# ============================================================
# 📂 ПУТИ К ТЕСТАМ
# ============================================================
testpaths = tests

# ============================================================
# 🏷️ РЕГИСТРАЦИЯ КАСТОМНЫХ МАРКЕРОВ
# ============================================================
markers =

    # ------------------------------------------------------------
    # 🌌 ТИПЫ ПРОГОНОВ 
    # ------------------------------------------------------------
    regress: Регрессионные тесты (основной прогон)
    
    # ------------------------------------------------------------
    # 🛰️ СТРАНИЦЫ 
    # ------------------------------------------------------------
    login: Тесты для страницы авторизации (login.html)
    dashboard: Тесты для страницы дашборда (dashboard.html)
    index: Тесты для страницы индекса (index.html)
    signup: Тесты для страницы регистрации (signup.html)
    access_restoration: Тесты страницы востановления (access-restoration.html)

    # ------------------------------------------------------------
    # 🎯 КАТЕГОРИИ ТЕСТОВ UI
    # ------------------------------------------------------------
    states: Состояния UI, анимации, визуальная валидация элементов
    workflows: Полные рабочие сценарии (Uplink → Logout)
    errors_ui: Негативные сценарии, защита и обработка ошибок
    interactions: Интерактивность, тултипы, hover-эффекты и навигация

    # ------------------------------------------------------------
    # 📝 КАТЕГОРИИ ТЕСТОВ ФОРМ
    # ------------------------------------------------------------
    success: Позитивные сценарии  
    errors: Негативные сценарии и ошибки
    validation: Валидация полей, ограничения ввода и санитизация 
    ui_navigation: UI-состояния, реактивность элементов и навигация 
