[pytest]

# ============================================================
# ⚙️ НАСТРОЙКИ ЗАПУСКА
# ============================================================
addopts =
    -s
    --clean-alluredir
    --alluredir=allure-results

# ============================================================
# 📂 ПУТИ К ТЕСТАМ
# ============================================================
testpaths = tests

# ============================================================
# 🏷️ РЕГИСТРАЦИЯ КАСТОМНЫХ МАРКЕРОВ
# ============================================================
markers =

    # ------------------------------------------------------------
    #  🌌 ТИПЫ ПРОГОНОВ (Сьюты)
    # ------------------------------------------------------------
    regress: Регрессионные тесты (основной прогон)
    
    # ------------------------------------------------------------
    # 🛰️ СТРАНИЦЫ (Компоненты)
    # ------------------------------------------------------------
    login: Тесты для страницы авторизации (/login.html)

    # ------------------------------------------------------------
    # 🧪 ТИПЫ ТЕСТОВ (Уровни)
    # ------------------------------------------------------------
    basic: Базовые сценарии и позитивные проверки
    validation: Валидация полей и негативные сценарии
    edge_cases: Граничные значения, безопасность и UI/UX
   
    
   
    
  
